<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>vs</string>
		<string>fs</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~G</string>
	<key>name</key>
	<string>GLSL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(void|bool|int|uint|float|vec2|vec3|vec4)\b</string>
			<key>name</key>
			<string>storage.type.glsl</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.glsl</string>
	<key>uuid</key>
	<string>D0FD1B52-F137-4FBA-A148-B8A893CD948C</string>
</dict>
</plist>
